-- =====================================================================
--  STEP 3 — LÕI BÁN HÀNG (Sales Core)
--  Tạo 2 bảng: chat_logs (nhật ký hội thoại) + leads (khách để lại liên hệ)
--  Chạy 1 lần trong Supabase → SQL Editor → New query → Run.
--  An toàn chạy lại nhiều lần (IF NOT EXISTS).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) BẢNG chat_logs — mỗi dòng là 1 tin nhắn (khách hoặc agent)
--    server.ts::logChatTurn() chèn 2 dòng mỗi lượt: sender='user' và sender='agent'
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chat_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  TEXT        NOT NULL,
  sender      TEXT        NOT NULL,           -- 'user' | 'agent'
  text        TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Lấy nhanh toàn bộ tin theo phiên, sắp theo thời gian.
CREATE INDEX IF NOT EXISTS idx_chat_logs_session
  ON public.chat_logs (session_id, created_at);

-- Lọc/nhóm hội thoại gần đây (màn quản trị).
CREATE INDEX IF NOT EXISTS idx_chat_logs_created
  ON public.chat_logs (created_at DESC);


-- ---------------------------------------------------------------------
-- 2) BẢNG leads — khách để lại SĐT (tự động phát hiện trong chat, hoặc form)
--    server.ts::saveLead() chống trùng theo phone trước khi chèn.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.leads (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  TEXT,
  name        TEXT,
  phone       TEXT,
  note        TEXT,
  source      TEXT        DEFAULT 'chat',      -- 'chat_auto' | 'form' | 'chat'
  status      TEXT        DEFAULT 'new',       -- 'new' | 'called' | 'won' | 'lost'
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Danh sách lead mới nhất (màn quản trị).
CREATE INDEX IF NOT EXISTS idx_leads_created
  ON public.leads (created_at DESC);

-- Chống trùng & tra cứu theo số điện thoại.
CREATE INDEX IF NOT EXISTS idx_leads_phone
  ON public.leads (phone);

-- Lọc theo trạng thái xử lý.
CREATE INDEX IF NOT EXISTS idx_leads_status
  ON public.leads (status);


-- =====================================================================
--  (TÙY CHỌN) BẢO MẬT RLS — BẬT KHI SẴN SÀNG
--  Server dùng SERVICE ROLE KEY nên KHÔNG bị RLS chặn (vẫn ghi/đọc bình thường).
--  Bật RLS để CHẶN client ẩn danh (anon key) đọc trực tiếp 2 bảng này.
--  Bỏ ghi chú (--) các dòng dưới nếu muốn bật ngay.
-- =====================================================================
-- ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.leads     ENABLE ROW LEVEL SECURITY;
-- Không tạo policy cho anon => anon bị chặn hoàn toàn; service role vẫn qua được.
