-- =====================================================================
--  NÂNG CẤP — ĐÁNH GIÁ CÂU TRẢ LỜI (👍 / 👎)
--  Tạo bảng answer_feedback: lưu lượt khách bấm thích / không thích dưới câu trả lời của agent.
--  Chạy 1 lần trong Supabase → SQL Editor → New query → Run. An toàn chạy lại (IF NOT EXISTS).
--
--  LƯU Ý: nếu bạn CHƯA chạy file STEP5_ANSWER_GAPS.sql thì hãy chạy cả file đó,
--  vì phần "Câu hỏi agent chưa trả lời được" cần bảng answer_gaps.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.answer_feedback (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  TEXT,
  rating      TEXT        NOT NULL,          -- 'up' | 'down'
  question    TEXT,                          -- câu khách hỏi (ngữ cảnh)
  answer      TEXT,                          -- câu agent đã trả lời
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Thống kê theo thời gian (dashboard).
CREATE INDEX IF NOT EXISTS idx_answer_feedback_created
  ON public.answer_feedback (created_at DESC);

-- Lọc nhanh theo loại đánh giá.
CREATE INDEX IF NOT EXISTS idx_answer_feedback_rating
  ON public.answer_feedback (rating);
