-- =====================================================================
--  NÂNG CẤP — PHÁT HIỆN CÂU HỎI AGENT CHƯA TRẢ LỜI ĐƯỢC (Answer Gaps)
--  Tạo bảng answer_gaps: lưu những câu khách hỏi mà agent trả lời "chưa có thông tin".
--  Chạy 1 lần trong Supabase → SQL Editor → New query → Run. An toàn chạy lại (IF NOT EXISTS).
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.answer_gaps (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  TEXT,
  question    TEXT        NOT NULL,          -- câu khách hỏi
  answer      TEXT,                          -- câu agent đã trả lời (thể hiện việc thiếu thông tin)
  status      TEXT        DEFAULT 'new',     -- 'new' | 'resolved' (đã bổ sung FAQ)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Lấy nhanh các lỗ hổng mới nhất / còn tồn.
CREATE INDEX IF NOT EXISTS idx_answer_gaps_created
  ON public.answer_gaps (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_answer_gaps_status
  ON public.answer_gaps (status);
